name: NPM Package CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  ci:
    name: Package CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint package code
        run: pnpm run lint

      - name: Build package
        run: pnpm run build

      - name: Unit tests
        run: pnpm run test

      - name: Full test suite (Integration + E2E)
        run: pnpm run test:all
        if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
